import createClient from 'openapi-fetch';
import type { paths } from './types';

export interface UlupSpacesClientOptions {
  /** Personal API key generated from Profile → API Keys on ulupspaces.com. */
  apiKey: string;
  /** Override the base URL — mainly useful for local development. Defaults to production. */
  baseUrl?: string;
}

export class UlupSpacesError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.name = 'UlupSpacesError';
    this.status = status;
  }
}

// Thin wrapper around openapi-fetch, typed 1:1 from the OpenAPI spec
// (types.ts is generated by openapi-typescript from openapi.yaml — don't
// edit it by hand, regenerate it when the spec changes). This class adds
// only: automatic Bearer header, readable method names instead of
// client.POST('/path', ...), and real JS exceptions instead of a
// { data, error, response } tuple to check by hand on every call.
export class UlupSpacesClient {
  private client: ReturnType<typeof createClient<paths>>;

  constructor(options: UlupSpacesClientOptions) {
    this.client = createClient<paths>({
      baseUrl: options.baseUrl ?? 'https://www.ulupspaces.com/api/v1',
      headers: { Authorization: `Bearer ${options.apiKey}` },
    });
  }

  private unwrap<T>(data: T | undefined, error: { error?: string } | undefined, response: Response): T {
    if (error || !response.ok) {
      throw new UlupSpacesError(error?.error ?? response.statusText, response.status);
    }
    return data as T;
  }

  /** Create a new project. */
  async createProject(name: string) {
    const { data, error, response } = await this.client.POST('/projects', {
      body: { name },
    });
    return this.unwrap(data, error, response);
  }

  /** List a project's nodes — structure only (id, name, task counts), never task text. */
  async listNodes(projectId: number) {
    const { data, error, response } = await this.client.GET('/projects/{id}/nodes', {
      params: { path: { id: projectId } },
    });
    return this.unwrap(data, error, response);
  }

  /** Create a node in a project. Duplicate-checked by name — see `duplicateOf`/`similarTo` on the result. */
  async createNode(projectId: number, name: string, color?: 'blue' | 'purple' | 'green') {
    const { data, error, response } = await this.client.POST('/projects/{id}/nodes', {
      params: { path: { id: projectId } },
      body: { name, color },
    });
    return this.unwrap(data, error, response);
  }

  /** Full project state: nodes, task text, and connections. */
  async getOverview(projectId: number) {
    const { data, error, response } = await this.client.GET('/projects/{id}/overview', {
      params: { path: { id: projectId } },
    });
    return this.unwrap(data, error, response);
  }

  /** Connect two existing nodes by name. Direction-agnostic — A→B and B→A count as the same link. */
  async connectNodes(projectId: number, sourceNodeName: string, targetNodeName: string) {
    const { data, error, response } = await this.client.POST('/nodes/connect', {
      body: { project_id: projectId, source_node_name: sourceNodeName, target_node_name: targetNodeName },
    });
    return this.unwrap(data, error, response);
  }

  /** Add a task to a node. */
  async addTask(nodeId: number, content: string) {
    const { data, error, response } = await this.client.POST('/nodes/{id}/tasks', {
      params: { path: { id: nodeId } },
      body: { content },
    });
    return this.unwrap(data, error, response);
  }

  /** Mark a task complete (default) or incomplete. */
  async completeTask(taskId: number, completed = true) {
    const { data, error, response } = await this.client.PATCH('/tasks/{id}', {
      params: { path: { id: taskId } },
      body: { completed },
    });
    return this.unwrap(data, error, response);
  }
}