/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project id
                 * @example 293
                 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List a project's nodes (structure only, not content) */
        get: operations["listProjectNodes"];
        put?: never;
        /**
         * Create a node in a project
         * @description Automatically checks for likely duplicates: if a node with an identical name already exists, it's reused instead of creating a new one (see `duplicateOf` in the response). If a node with a similar but not identical name exists, the new node is still created, with `similarTo` flagging it.
         */
        post: operations["createNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project id
                 * @example 293
                 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * Full current state of the project
         * @description Unlike `GET /projects/{id}/nodes`, this also includes the actual text of tasks (not just counts) and every connection between nodes. Use it when you need to read real content, not just structure.
         */
        get: operations["getProjectOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect two existing nodes, by name
         * @description A connection is considered the same regardless of direction: connecting A→B when B→A already exists does not create a duplicate (see `alreadyConnected` in the response).
         */
        post: operations["connectNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Node id
                 * @example 1263
                 */
                id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a task to a node */
        post: operations["addTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Task id
                 * @example 1060
                 */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a task complete or incomplete */
        patch: operations["completeTask"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            id: number;
            name: string;
        };
        /** @description Structural node metadata — never the text of its tasks. */
        NodeStructure: {
            id: number;
            name: string;
            totalTasks: number;
            completedTasks: number;
        };
        CreateNodeResult: {
            id: number;
            name: string;
            /** @description Present only if a node with an identical name already existed (reused instead of creating a new one). */
            duplicateOf?: {
                id: number;
                name: string;
            } | null;
            /** @description Present only if a node with a similar, non-identical name exists. */
            similarTo?: {
                id: number;
                name: string;
            } | null;
        };
        Connection: {
            source: string;
            target: string;
            alreadyConnected?: boolean | null;
        };
        Task: {
            id: number;
            content: string;
        };
        ProjectOverview: {
            name: string;
            nodes: {
                id: number;
                name: string;
                color: string;
                tasks: {
                    id: number;
                    content: string;
                    completed: boolean;
                }[];
            }[];
            connections: components["schemas"]["Connection"][];
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description Invalid request (missing or malformed parameter) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or revoked API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found, or not owned by the key's user */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Project id
         * @example 293
         */
        ProjectId: number;
        /**
         * @description Node id
         * @example 1263
         */
        NodeId: number;
        /**
         * @description Task id
         * @example 1060
         */
        TaskId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Podcast Launch */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjectNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project id
                 * @example 293
                 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeStructure"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project id
                 * @example 293
                 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Recording */
                    name: string;
                    /**
                     * @default blue
                     * @enum {string}
                     */
                    color?: "blue" | "purple" | "green";
                };
            };
        };
        responses: {
            /** @description Node created (or reused, if an exact duplicate) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateNodeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProjectOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Project id
                 * @example 293
                 */
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full project state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOverview"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    connectNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 293 */
                    project_id: number;
                    /** @example Recording */
                    source_node_name: string;
                    /** @example Editing */
                    target_node_name: string;
                };
            };
        };
        responses: {
            /** @description Connection created (or already existed) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Node id
                 * @example 1263
                 */
                id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Record intro */
                    content: string;
                };
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Task id
                 * @example 1060
                 */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description If omitted, defaults to `true`.
                     * @default true
                     */
                    completed?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        completed: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}